services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: device_db
    volumes:
      - mongodb-data:/data/db/
      - ./db/init.js:/docker-entrypoint-initdb.d/init-db.js
    networks:
      - net

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      mongodb:
        condition: service_started
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    networks:
      - net

volumes:
  mongodb-data:
    driver: local

networks:
  net:
    driver: bridge
