services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: device_db
    volumes:
      - ./db/init.js:/docker-entrypoint-initdb.d/init-db.js
    networks:
      - net

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      mongo:
        condition: service_started
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    networks:
      - net

  app:
    build:
      context: .
    depends_on:
      mongo:
        condition: service_started
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      JAVA_OPTS: >-
        -XX:+UseG1GC
        -XX:MaxRAMPercentage=90
        -XX:MinRAMPercentage=70
        -XX:InitialRAMPercentage=50
    networks:
      - net

networks:
  net:
    driver: bridge
