services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: device_db
    volumes:
      - ./db/init.js:/docker-entrypoint-initdb.d/init-db.js
    networks:
      - net

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      mongo:
        condition: service_started
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    networks:
      - net

  jaeger:
    image: jaegertracing/jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      COLLECTOR_OTLP_ENABLED: true
    networks:
      - net

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    restart: always
    command:
      - start-dev
      - --import-realm
    depends_on:
      jaeger:
        condition: service_started
    ports:
      - "8083:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_TRACING_ENABLED: true
      KC_TRACING_SAMPLER_TYPE: always_on
      KC_TRACING_ENDPOINT: http://jaeger:4317
    volumes:
      - ./kc:/opt/keycloak/data/import
    networks:
      - net

  kc-healthchecker:
    image: curlimages/curl
    restart: on-failure
    command:
      - --fail
      - http://keycloak:9000/health
    depends_on:
      keycloak:
        condition: service_started
    networks:
      - net

  app:
    build:
      context: .
    depends_on:
      mongo:
        condition: service_started
      jaeger:
        condition: service_started
      kc-healthchecker:
        condition: service_completed_successfully
    profiles: [ prod ]
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      JAVA_OPTS: >-
        -XX:+UseG1GC
        -XX:MaxRAMPercentage=90
        -XX:MinRAMPercentage=70
        -XX:InitialRAMPercentage=50
    networks:
      - net

networks:
  net:
    driver: bridge
