spring:
  data:
    mongodb:
      host: 'mongo'
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://keycloak:8080/realms/master/protocol/openid-connect/certs'

management:
  otlp:
    tracing:
      endpoint: 'http://jaeger:4317'
