spring:
  application:
    name: 'device-service'
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      host: 'localhost'
      database: 'device_db'
      username: 'device_service'
      password: 'device@app'
      uuid-representation: standard

open-api:
  title: "Device Service"
  version: "1.0.0"
  description: "Service responsible for managing device resources"
  author: "mggoes"
  email: "matheus.ggoes@outlook.com"
