spring:
  application:
    name: 'device-service'
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      host: 'localhost'
      database: 'device_db'
      username: 'device_service'
      password: 'device@app'
      uuid-representation: standard
