spring:
  application:
    name: 'device-service'
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      host: 'localhost'
      database: 'device_db'
      username: 'device_service'
      password: 'device@app'
      uuid-representation: standard

management:
  server:
    port: 8083
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents,metrics
  endpoint:
    health:
      show-details: always

open-api:
  title: "Device Service"
  version: "1.0.0"
  description: "Service responsible for managing device resources"
  author: "mggoes"
  email: "matheus.ggoes@outlook.com"
