spring:
  application:
    name: 'device-service'
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      host: 'localhost'
      database: 'device_db'
      username: 'device_service'
      password: 'device@app'
      uuid-representation: standard
  security:
    oauth2:
      client:
        registration:
          keycloak:
            authorization-grant-type: 'client_credentials'
            client-id: 'device-service'
            client-secret: 'ymWPrMbHMGvgJHLBR3gYYxAYkOSUdUHd'
        provider:
          keycloak:
            token-uri: 'http://localhost:8083/realms/master/protocol/openid-connect/token'
            authorization-uri: 'http://localhost:8083/realms/master/protocol/openid-connect/auth'
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:8083/realms/master'

management:
  server:
    port: 8081
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents,metrics
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
    instances:
      save-device-cb: &default-cb-config
        failure-rate-threshold: 50
        slow-call-duration-threshold: 2s
        sliding-window-size: 2
        minimum-number-of-calls: 2
        slow-call-rate-threshold: 100
        sliding-window-type: COUNT_BASED
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 3
        ignore-exceptions:
          - br.com.device.exception.DeviceInUseException
          - br.com.device.exception.DeviceNotFoundException
      read-all-devices-cb: *default-cb-config
      read-one-device-cb: *default-cb-config
      update-device-cb: *default-cb-config
      delete-device-cb: *default-cb-config
  retry:
    instances:
      read-all-devices-retry: &default-retry-config
        max-attempts: 3
        wait-duration: 1s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        ignore-exceptions:
          - br.com.device.exception.DeviceInUseException
          - br.com.device.exception.DeviceNotFoundException
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
      read-one-device-retry: *default-retry-config

springdoc:
  swagger-ui:
    oauth:
      client-id: '${spring.security.oauth2.client.registration.keycloak.client-id}'
      client-secret: '${spring.security.oauth2.client.registration.keycloak.client-secret}'
  auth-flow:
    token-url: '${spring.security.oauth2.client.provider.keycloak.token-uri}'
    authorization-url: '${spring.security.oauth2.client.provider.keycloak.authorization-uri}'
  basic:
    title: "Device Service"
    version: "1.0.0"
    description: "Service responsible for managing device resources"
    author: "mggoes"
    email: "matheus.ggoes@outlook.com"
